name: Update and Commit Feed Cache

on:
  schedule:
    - cron: '7 0-3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser beautifulsoup4
        
      - name: Run feed script
        run: |
          python generate_feeds.py | tee output.log  # ðŸš€ Captura logs
        shell: bash
        
    - name: Run Python script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python send_rss_to_telegram.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Stash unstaged changes (if any)
      run: |
        if [[ `git status --porcelain` ]]; then
          git stash --include-untracked
        fi

    - name: Pull latest changes with rebase
      run: |
        git pull --rebase origin main

    - name: Apply stashed changes (if any)
      run: |
        if git stash list | grep -q 'stash@{0}'; then
          git stash pop
        fi

    - name: Commit changes
      run: |
        if [[ `git status --porcelain` ]]; then
          git add feed_cache.json
          git commit -m "Update and Commit Feed Cache"
          git push origin main
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
